# Generated by Django 5.0.6 on 2024-09-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='graduating_class',
            field=models.CharField(choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028'), ('not_applicable', 'Not Applicable')], default='not_applicable', max_length=20),
        ),
    ]
