# Generated by Django 5.0.6 on 2024-09-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
