# Generated by Django 5.0.6 on 2024-09-16 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='college',
            field=models.CharField(choices=[('orfalea', 'Orfalea College of Business'), ('bailey', 'Bailey College of Science and Mathematics'), ('agriculture', 'College of Agriculture, Food and Environmental Sciences'), ('architecture', 'College of Architecture and Environmental'), ('liberal_arts', 'College of Liberal Arts'), ('engineering', 'College of Engineering'), ('not_applicable', 'Not Applicable')], max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='graduating_class',
            field=models.CharField(blank=True, choices=[('2024', '2024'), ('2025', '2025'), ('2026', '2026'), ('2027', '2027'), ('2028', '2028')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('faculty_staff', 'Faculty/Staff')], max_length=20),
        ),
    ]
