# Generated by Django 5.0.6 on 2024-09-18 14:27

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def generate_unique_date(apps, schema_editor):
    Word = apps.get_model('wordle', 'Word')
    date = datetime.date(2024, 9, 18)  # Start from this date
    for word in Word.objects.all():
        word.date = date
        word.save()
        date += datetime.timedelta(days=1)  # Increment by one day for each word



class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='date_used',
        ),
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateField(default=datetime.date(2024, 9, 18), unique=True),
            preserve_default=False,
        ),
        migrations.RunPython(generate_unique_date),   
        migrations.CreateModel(
            name='UserGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_played', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wordle.word')),
            ],
            options={
                'unique_together': {('user', 'date_played')},
            },
        ),
    ]
