# Generated by Django 5.0.6 on 2024-09-13 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='date',
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaderboard',
            name='last_played',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='leaderboard',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
