# Generated by Django 5.0.6 on 2024-09-18 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_remove_word_date_used_word_date_usergame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(),
        ),
    ]
