# Generated by Django 5.0.6 on 2024-09-14 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0002_remove_leaderboard_date_leaderboard_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaderboard',
            name='user',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='user',
        ),
        migrations.DeleteModel(
            name='GuessDetail',
        ),
        migrations.DeleteModel(
            name='Leaderboard',
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
