# Generated by Django 5.0.6 on 2024-09-18 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_alter_word_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergame',
            name='word',
        ),
        migrations.AlterField(
            model_name='usergame',
            name='date_played',
            field=models.DateField(),
        ),
    ]
