# Generated by Django 5.0.6 on 2024-09-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0003_remove_leaderboard_user_remove_setting_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='length',
        ),
        migrations.AddField(
            model_name='word',
            name='date_used',
            field=models.DateField(null=True),
        ),
    ]
