# Generated by Django 5.0.6 on 2024-09-15 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0004_remove_word_length_word_date_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='time_played',
            field=models.IntegerField(default=0),
        ),
    ]
