# Generated by Django 5.0.6 on 2024-09-15 22:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordle', '0005_game_time_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuessTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken', models.FloatField()),
                ('guess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time', to='wordle.guess')),
            ],
        ),
    ]
